baseURL = 'https://swiftzer.net/'
languageCode = 'zh-TW'
title = 'Swiftzer'
theme = 'LoveIt'


# Author config
[author]
  name = "Swiftzer"
  email = "info@swiftzer.net"
  link = "https://swiftzer.net"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""


# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false



[permalinks]
  posts = '/:year/:month/:title/'

defaultContentLanguage = 'zh-tw'
